services:
  api:
    conatiner_name: api
    build: ./api
    pots:
      - 8080:8080
    tty: true
    volumes:
      - ./api:/workspace:cached

  web:
    container_name: web
    build: ./web
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./web:/workspace:cached
    dependes_on:
      - api