name: Deploy Simple CI/CD

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-east-1
  ECS_SERVICE: simple-cicd-service
  ECS_CLUSTER: simple-cicd-cluster
  ECS_TASK_DEFINITION: .aws/task-definition.json

permissions:
  contents: read

jobs:
# Web Container Build/Test
## Get Source
## Build/Test
## Docker Image Build
## Login AWS
## Push image to ECR

# API Container Build/Test
## Get Source
## Build/Test
## Docker Image Build
## Login AWS
## Push image to ECR

# Deploy
## Get Source
## Login AWS
## Edit Task Definition
## Deploy
