name: Deploy Simple CI/CD

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-east-1
  ECS_SERVICE: simple-cicd-service
  ECS_CLUSTER: simple-cicd-cluster
  ECS_TASK_DEFINITION: .aws/task-definition.json

permissions:
  contents: read

jobs:
  web-test-build-image:
    name: Web Container - Test and Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v3

      - name: Build an Image and Run Tests
        run: |
          docker image build --target production -t -temp_web_image_name:latest --build-arg REACT_APP_API_SERVER=/api .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-access-access-key: ${{ secrets.AWS_ACCESS_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_WEB_SERVER_REPOSITORY }}
        run: |
          docker image tag temp_web_image_name:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
# Web Container Build/Test
## Get Source
## Build/Test
## Docker Image Build
## Login AWS
## Push image to ECR

# API Container Build/Test
## Get Source
## Build/Test
## Docker Image Build
## Login AWS
## Push image to ECR

# Deploy
## Get Source
## Login AWS
## Edit Task Definition
## Deploy
